version: "3.7"

services:
  petsy-search:
    image: michaelkoconnor/petsy-search
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 5001:5001
      - 3000:3000
    env_file: .env.prod
    restart: unless-stopped
